name: test_cli2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.jpg
    - assets/images/avatar2.jpg
    - assets/property/house1.jpg
    - assets/property/house2.jpg
    - assets/property/house3.jpg
